export const BASE_PATH_URL = '';
export const NB_MAX_PAGES = 3; // number of pages to scrappe
export const PAUSE_DELAY = 1000;
export const NUMBER_RESULTS_DISPLAYED = 5;

export const KEYWORDS_WHITELIST = [
	'PLATEAU',
	'Patrie',
	'Petite',
	'Plateau',
	'ROSEMONT',
	'Rosemont',
	'WESTMOUNT',
	'Westmount',
	'balcon',
	'balcony',
	'italie',
	'italy',
	'laurier',
	'metro',
	'mont-royal',
	'métro',
	'patrie',
	'plateau',
	'rosemont',
	'terasse',
	'westmount',
];

export const KEYWORDS_BLACKLIST = [
	'H-Beaugrand',
	'Henri-Bourassa',
	'Honoré-Beaugrand',
	'LaSalle',
	'McGill Student',
	'VSL',
	'Ville Saint-Laurent',
	'West Island',
	'ahuntsic',
	'assomption',
	'basement',
	'bourassa',
	'cadillac',
	'cartier',
	'cartierville',
	'cremazie',
	'dorval',
	'echange',
	'exchange',
	'fabre',
	'henri',
	'hochelaga',
	'jarry',
	'langelier',
	'lasalle',
	'laval',
	'longueil',
	'masson',
	'mercier',
	'homa',
	'molson',
	'nord',
	'pierrefonds',
	'sous-sol',
	'st-michel',
	'student',
	'students',
	'suspendue',
	'swap',
	'verdun',
	'viau',
	'villeray',
];
